apiVersion: v1
kind: Service
metadata:
  name: zendesk-exporter
  labels:
    app.kubernetes.io/name: zendesk-exporter
    app.kubernetes.io/component: monitoring
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9091
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: zendesk-exporter
